name: Release Charts

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  test_bom_action:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install bom and test presence in path
    steps:
      - name: Install bom
        uses: puerco/release-actions/setup-bom@main
      - name: Check install!
        run: bom version